### ISSUE TITLE
App ideas

### ISSUE THREAD

**Issue by italojar** [italojar/ArchitectCodersApp#1]
- Present ideas and come up with a common idea.
- Choose the name of the app.
- Define what the app is going to be about.

**Comment by P3r1c086** [comment]
My suggestions for app name: 
- Nasa Explorer
- Nasa
- Space Explorers

**Comment by P3r1c086** [comment]
Example for the color palette: 
![Paleta colores 1](https://github.com/italojar/ArchitectCodersApp/assets/80258593/f9484f60-6a95-41dc-8150-12de04eddb4d)
![Paleta colores 2](https://github.com/italojar/ArchitectCodersApp/assets/80258593/5d27ab26-131a-46d5-b2b8-8f07a0e8dfeb)

**Comment by italojar** [comment]
We choose "Space Explorer" as the name of the application and the first color palette by adding a white color.
